apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS testdb;
    GRANT ALL PRIVILEGES ON testdb.* TO 'user'@'%';
